version: '3'
services:

  gloo:
    image: soloio/gloo:0.2.4
    entrypoint: ["/gloo"]
    working_dir: /config/
    command:
    - "--storage.type=file"
    - "--storage.refreshrate=1s"
    - "--secrets.type=file"
    - "--secrets.refreshrate=1s"
    volumes:
    - ./gloo-config:/config/

  ingress:
    image: soloio/envoy:v0.1.6-132
    entrypoint: ["envoy"]
    command: ["-c", "/config/envoy.yaml", "--v2-config-only"]
    volumes:
    - ./envoy.yaml:/config/envoy.yaml:ro
    ports:
    - "8080:8080"
    - "19000:19000"
